### ISSUE TITLE
changing the horizon to 5 gives RuntimeError: The size of tensor a (13) must match the size of tensor b (31) at non-singleton dimension 1

### ISSUE THREAD

**Issue by rohitsaluja22** [valeoai/BEEF#3]
Hi, I am able to successfully run the code for 3 fps and horizon = 2. when I process the videos again for horizon = 5, the processing gets completed nicely but during training I get following error:
```
^[[1m^[[90m[I 2022-02-24 11:46:26]^[[0m .../criterions/factory.py.16: Creating criterion from bootstrap for eval mode...
^[[1m^[[90m[I 2022-02-24 11:46:26]^[[0m ...els/metrics/factory.py.14: Creating metric from bootstrap for train mode...
^[[1m^[[90m[I 2022-02-24 11:46:34]^[[0m ...els/metrics/factory.py.14: Creating metric from bootstrap for eval mode...
^[[1m^[[90m[I 2022-02-24 11:46:39]^[[0m .../optimizers/factory.py.31: Creating optimizer adam ...
^[[1m^[[90m[I 2022-02-24 11:46:39]^[[0m ...strap/views/factory.py.7: Creating views...
^[[1m^[[90m[I 2022-02-24 11:46:45]^[[0m ...trap/engines/engine.py.113: Launching training procedures
^[[1m^[[90m[I 2022-02-24 11:46:45]^[[0m ...trap/engines/engine.py.151: Training model on trainset for epoch 0
^[[1m^[[90m[I 2022-02-24 11:46:49]^[[0m ...kages/bootstrap/run.py.120: Traceback (most recent call last):
File "/home/rohit.saluja/miniconda3/envs/beef/lib/python3.7/site-packages/bootstrap/run.py", line 113, in main
    run(path_opts=path_opts)
  File "/home/rohit.saluja/miniconda3/envs/beef/lib/python3.7/site-packages/bootstrap/run.py", line 104, in run
    engine.train()
  File "/home/rohit.saluja/miniconda3/envs/beef/lib/python3.7/site-packages/bootstrap/engines/engine.py", line 117, in train
    self.train_epoch(self.model, self.dataset['train'], self.optimizer, self.epoch)
  File "/home/rohit.saluja/miniconda3/envs/beef/lib/python3.7/site-packages/bootstrap/engines/engine.py", line 170, in train_epoch
    out = model(batch)
  File "/home/rohit.saluja/miniconda3/envs/beef/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rohit.saluja/miniconda3/envs/beef/lib/python3.7/site-packages/bootstrap/models/model.py", line 77, in forward
    cri_tmp = self.criterions[self.mode](net_out, batch)
  File "/home/rohit.saluja/miniconda3/envs/beef/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rohit.saluja/BEEF5sec/models/criterions/multitask.py", line 23, in forward
    out_traj = self.traj_loss(net_out, batch)
  File "/home/rohit.saluja/miniconda3/envs/beef/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rohit.saluja/BEEF5sec/models/criterions/l2_points.py", line 19, in forward
    diff = pred_xy - gt_xy
RuntimeError: The size of tensor a (13) must match the size of tensor b (31) at non-singleton dimension 1
 3
 ```
Please suggest what could have gone wrong. Do I need to change anything else in the code which I am missing?

Thanks

**Comment by EloiZ** [comment]
Hi,
sorry for late reply, did you manage to make it work?
